title: "GSoC’25 Proposal Review | {{Project Name}} ({{Your Name}})"
body:
- type: input
  attributes:
    label: Google Doc link to proposal
    description: "Please paste the Google Doc link to the proposal here."
  validations:
    required: true
- type: checkboxes
  id: sharing
  attributes:
    label: I confirm that I have given edit access to the GSoC mentors mailing list.
    description: >
        Note: If you're concerned about unwanted changes, you can turn on
        [edit notifications](https://support.google.com/docs/answer/91588?hl=en&co=GENIE.Platform%3DDesktop).
    options:
        - label: "Yes"
          required: true
- type: dropdown
  id: review-section
  attributes:
    label: Which section should the reviewer take a look at?
    options:
      - "3.1: WHAT"
      - "3.2: HOW"
      - "Both 3.1: WHAT and 3.2: HOW"
  validations:
    required: true
- type: textarea
  id: additional
  attributes:
    label: Additional information
    description: |
        Add any other information about the proposal here.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
